local rarities = {}

rarities.rarityColors = {
    ["godly"] = Color3.new(0.933333, 0.92549, 0.435294),
    ["lengendary"] = Color3.new(0.639216, 0.278431, 0.278431),
    ["rare"] = Color3.new(0.372549, 0.607843, 0.721569),
    ["uncommon"] = Color3.new(0.588235, 0.72549, 0.509804),
    ["common"] = Color3.new(0.4, 0.4, 0.4);
}

rarities.rarityItemTypes = {
    "weapon",
    "consumable",
    "resource";
}

return rarities